apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-demo
spec:
  project: default
  source:
    repoURL: https://github.com/rcorderoayigroup/helm-demo.git
    path: .
    targetRevision: HEAD
    helm:
      values: |
        replicas: 2
        image: nginx:1.25
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated: {}